import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  atlasSidebar: [
    'intro',
    {
      type: 'category',
      label: '案例库',
      items: [{type: 'autogenerated', dirName: 'cases'}],
    },
    {
      type: 'category',
      label: '架构模式',
      items: [{type: 'autogenerated', dirName: 'patterns'}],
    },
    {
      type: 'category',
      label: '设计题',
      items: [{type: 'autogenerated', dirName: 'questions'}],
    },
    {
      type: 'category',
      label: '学习路径',
      items: [{type: 'autogenerated', dirName: 'paths'}],
    },
    {
      type: 'category',
      label: '资料库',
      items: [{type: 'autogenerated', dirName: 'references'}],
    },
  ],
};

export default sidebars;
