import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import test from 'node:test';

import {requiredCaseSlugs} from '../scripts/content-schema.mjs';

const root = new URL('../', import.meta.url);

async function source(path) {
  return readFile(new URL(path, root), 'utf8');
}

test('uses one root autogenerated sidebar instead of duplicate manual categories', async () => {
  const sidebar = await source('sidebars.ts');

  assert.match(sidebar, /type:\s*'autogenerated'/);
  assert.match(sidebar, /dirName:\s*'\.'/);
  assert.doesNotMatch(sidebar, /label:\s*'案例库'/);
  assert.doesNotMatch(sidebar, /dirName:\s*'cases'/);
});

test('orders section index links without rendering duplicate children', async () => {
  const expected = new Map([
    ['content/intro.mdx', 1],
    ['content/cases/index.mdx', 2],
    ['content/patterns/index.mdx', 3],
    ['content/questions/index.mdx', 4],
    ['content/paths/index.mdx', 5],
    ['content/references/index.mdx', 6],
  ]);

  for (const [path, position] of expected) {
    assert.match(await source(path), new RegExp(`sidebar_position: ${position}`));
  }
});

test('gives every canonical case a concise navigation-only label', async () => {
  for (const slug of requiredCaseSlugs) {
    const filename = slug.split('/').at(-1);
    const content = await source(`content/cases/${filename}.mdx`);
    const label = content.match(/^sidebar_label: (.+)$/m)?.[1];

    assert.ok(label, `Missing sidebar_label for ${slug}`);
    assert.ok(label.length <= 42, `Sidebar label is too long for ${slug}`);
    assert.doesNotMatch(label, /[：:]/, `Sidebar label contains a subtitle for ${slug}`);
  }
});

test('gives sidebar rows readable hierarchy and stable active feedback', async () => {
  const css = await source('src/css/custom.css');

  assert.match(css, /\.theme-doc-sidebar-menu\s*\{/);
  assert.match(
    css,
    /\.theme-doc-sidebar-menu \.menu__link\s*\{[^}]*min-height:\s*2\.5rem/s,
  );
  assert.match(
    css,
    /\.theme-doc-sidebar-menu \.menu__link--sublist\s*\{[^}]*font-weight:\s*650/s,
  );
  assert.match(
    css,
    /\.theme-doc-sidebar-menu \.menu__list \.menu__list\s*\{[^}]*padding-left:\s*0\.75rem/s,
  );
  assert.match(css, /text-overflow:\s*ellipsis/);
  assert.match(
    css,
    /\.theme-doc-sidebar-menu \.menu__link--active:not\(\.menu__link--sublist\)\s*\{[^}]*box-shadow:\s*inset 2px 0/s,
  );
  assert.doesNotMatch(
    css,
    /\.menu__link--active:not\(\.menu__link--sublist\)\s*\{[^}]*border-left:/s,
  );
});
